name: create-conda-env
description: 'Create conda environments if they dont exist'
runs:
  using: "composite"
  steps:
    - name: Create conda environments
      run: |
        conda env list
        if conda env list | grep -q "envs/${{ env.conda-env-name-no-time }}"; then
          echo "Using pre-existing conda environments with prefix ${{ env.conda-env-name-no-time }}"
        else
          echo "Creating a conda environment for each toolchain with the toolchain installed"
          ./build-setup.sh \
            --conda-env-name ${{ env.conda-env-name-no-time }}-$(date --date "${{ env.workflow-timestamp }}" +%Y%m%d) \
            --github-token ${{ github.token }} \
            --verbose \
            --skip-submodules \
            --skip-ctags \
            --skip-precompile \
            --skip-firesim \
            --skip-marshal \
            --skip-clean
        fi
      shell: bash -leo pipefail {0}
