run_farm:
    base_recipe: run-farm-recipes/externally_provisioned.yaml
    recipe_arg_overrides:
        default_platform: XilinxAlveoU250InstanceDeployManager
        default_simulation_dir: /scratch/buildbot/RUN_DIR
        run_farm_hosts_to_use:
            - a17: one_fpga_spec

metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: verilator
  metasimulation_only_plusargs: ""
  metasimulation_only_vcs_plusargs: ""

target_config:
    topology: no_net_config
    no_net_num_nodes: 1
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: alveo_u250_firesim_boom_singlecore_no_nic
    plusarg_passthrough: ""

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: outputs.json
    terminate_on_completion: no
    suffix_tag: null

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
