# Hardware config database for FireSim Simulation Manager

# The AGFIs provided below are public and available to all users.
# Only AGFIs for the latest release of FireSim are guaranteed to be available.
# If you are using an older version of FireSim, you will need to generate your
# own images.

# DOCREF START: Example HWDB Entry
firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
    agfi: agfi-04de4143495fbdadb
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
# DOCREF END: Example HWDB Entry
firesim_boom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0b7484cfa93e064d6
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_gemmini_printf_rocket_singlecore_no_nic:
    agfi: agfi-0ace16d35c5758893
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_gemmini_rocket_singlecore_no_nic:
    agfi: agfi-05eec5fb565f7cfa3
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_quadcore_nic_l2_llc4mb_ddr3:
    agfi: agfi-072cc9daac93249da
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_quadcore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0d0cbe59e2914492a
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_no_nic_l2_lbp:
    agfi: agfi-0cfc97258aa8389f0
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_nic_l2_llc4mb_ddr3:
    agfi: agfi-02e4056f9bec5a240
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0d8abef077c23a4de
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_no_nic_l2_llc4mb_ddr3_printf:
    agfi: agfi-033e840230f51668f
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
firesim_supernode_rocket_singlecore_nic_l2_lbp:
    agfi: agfi-0eae0fa36537e2835
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
vitis_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/11ba762decd46c5a933960eae699aaf551d6769f/vitis/vitis_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
vitis_firesim_gemmini_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/0af81b912264abbe3f90f8140987814291090560/vitis/vitis_firesim_gemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/167cd330431fbf2822ad53bcb11322cb6c845e15/xilinx_alveo_u250/alveo_u250_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_quadcore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/d87d1232dad4dd59ad3c0ebfb698eeff4b9f2c57/xilinx_alveo_u250/alveo_u250_firesim_rocket_quadcore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_boom_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/9fdc7e05d759a46717b7ae90fece95c054ae4751/xilinx_alveo_u250/alveo_u250_firesim_boom_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_rocket_singlecore_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/df431f268fc76631ba785e179f5c2f85433c68e4/xilinx_alveo_u250/alveo_u250_firesim_rocket_singlecore_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u250_firesim_gemmini_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/d22c9f278e9eaf4ed4130dd0bab737d8ade44f9c/xilinx_alveo_u250/alveo_u250_firesim_gemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u200_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/91e33fabf22cf951f29e231f160728ee8720d4d5/xilinx_alveo_u200/alveo_u200_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
alveo_u280_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/9f8c4a36389e6d9506ad79e3e4f38f43f7fa6fca/xilinx_alveo_u280/alveo_u280_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
xilinx_vcu118_firesim_rocket_singlecore_4GB_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/0f1f768a805af1c2c2d8d9fd6f4693ba6dec11a0/xilinx_vcu118/xilinx_vcu118_firesim_rocket_singlecore_4GB_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
nitefury_firesim_rocket_singlecore_no_nic:
    bitstream_tar: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/bd1eb4e58c30a7fd38bb332c76bfff2c2ca4823f/rhsresearch_nitefury_ii/nitefury_firesim_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    deploy_makefrag_override: ../../generators/firechip/chip/src/main/makefrag/firesim
    custom_runtime_config: null
