# adapted from https://github.com/chipsalliance/chisel/blob/main/.github/workflows/require-label.yml

name: Require Release Notes Label

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:v1.4.25
        with:
          one_of: changelog:added,changelog:changed,changelog:fixed,changelog:omit,changelog:removed
          repo_token: ${{ secrets.GITHUB_TOKEN }}
