name: update-circt

# update weekly
on:
  schedule:
    - cron: 0 0 * * 1

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  update-circt:
    name: update-circt
    runs-on: ubuntu-latest
    steps:
      - name: Update CIRCT
        uses: circt/update-circt@v1
        with:
          user: 'bartender'
          email: 'firesimchipyard@gmail.com'
          pr-reviewers: ''
          pr-labels: 'changelog:changed'
          circt-config: './conda-reqs/circt.json'
          github-token: ${{ secrets.BARTENDER_PERSONAL_ACCESS_TOKEN }}
